################################################################################
## plot figures showing different binding between AD and AF3 drugs
library(tidyverse)
library(readr)
library(ggplot2)
library(patchwork)
rm(list = ls())
#####-----0 setup -----#####

# Input folder generated by the PLIP summary script
base_dir <- "/Users/hc284/Documents/_0mpox/ADaf3out_Stats/plip_AF_AD_summary"

complex_file <- file.path(base_dir, "plip_complex_summary.csv")
counts_file  <- file.path(base_dir, "plip_counts_long.csv")
inter_file   <- file.path(base_dir, "plip_interactions_long.csv.gz")

outdir <- file.path(base_dir, "plots")
dir.create(outdir, showWarnings = FALSE, recursive = TRUE)

complex_df <- read_csv(complex_file, show_col_types = FALSE)
counts_df  <- read_csv(counts_file, show_col_types = FALSE)
inter_df   <- read_csv(inter_file, show_col_types = FALSE)

# Colors based on your AF/AD clustering plot
method_cols <- c(
  "AD" = "#2F6FA3",   # blue
  "AF" = "#D9A441"    # gold/yellow
)

set_cols <- c(
  "AD only" = "#2F6FA3",
  "Shared"  = "grey65",
  "AF only" = "#D9A441"
)

protein_levels <- c(
  "OPG027", "OPG092", "OPG112", "OPG120",
  "OPG154", "OPG174", "OPG198", "OPG199"
)

interaction_levels <- c(
  "hydrophobic",
  "hbond",
  "water_bridge",
  "salt_bridge",
  "pi_stack",
  "pi_cation",
  "halogen_bond",
  "metal_complex"
)

interaction_labels <- c(
  hydrophobic   = "Hydrophobic",
  hbond         = "H-bond",
  water_bridge  = "Water bridge",
  salt_bridge   = "Salt bridge",
  pi_stack      = "π-stack",
  pi_cation     = "π-cation",
  halogen_bond  = "Halogen bond",
  metal_complex = "Metal complex"
)

theme_nature_small <- function(base_size = 9) {
  theme_classic(base_size = base_size) +
    theme(
      text = element_text(color = "black"),
      axis.text = element_text(color = "black", size = base_size),
      axis.title = element_text(color = "black", size = base_size + 1),
      plot.title = element_text(size = base_size + 2, face = "bold", hjust = 0),
      strip.background = element_blank(),
      strip.text = element_text(size = base_size + 1, face = "bold"),
      legend.title = element_blank(),
      legend.text = element_text(size = base_size),
      legend.key.size = unit(0.4, "cm"),
      axis.line = element_line(linewidth = 0.35),
      axis.ticks = element_line(linewidth = 0.5),
      panel.spacing = unit(0.8, "lines")
    )
}

# Clean factor ordering
complex_df <- complex_df %>%
  mutate(
    protein = factor(protein, levels = protein_levels),
    method = factor(method, levels = c("AD", "AF"))
  )

counts_df <- counts_df %>%
  mutate(
    protein = factor(protein, levels = protein_levels),
    method = factor(method, levels = c("AD", "AF")),
    interaction_type = factor(interaction_type, levels = interaction_levels)
  )

inter_df <- inter_df %>%
  mutate(
    protein = factor(protein, levels = protein_levels),
    method = factor(method, levels = c("AD", "AF")),
    interaction_type = factor(interaction_type, levels = interaction_levels)
  )

#####----- Figure 1. AF and AD select different ligand sets -----#####
# This shows AF-only, shared, and AD-only ligands for each protein.
# One row per method / strain / protein / ligand
ligand_sets <- complex_df %>%
  filter(status == "success") %>%
  distinct(method, strain, protein, EBC_ID)

# Shared ligands for each strain-protein pair
overlap_df <- ligand_sets %>%
  group_by(strain, protein, EBC_ID) %>%
  summarise(n_methods = n_distinct(method), .groups = "drop") %>%
  group_by(strain, protein) %>%
  summarise(
    shared = sum(n_methods == 2),
    .groups = "drop"
  )

method_counts <- ligand_sets %>%
  group_by(strain, protein, method) %>%
  summarise(n_ligands = n_distinct(EBC_ID), .groups = "drop") %>%
  pivot_wider(
    names_from = method,
    values_from = n_ligands,
    values_fill = 0
  )

overlap_full <- method_counts %>%
  left_join(overlap_df, by = c("strain", "protein")) %>%
  mutate(
    shared = replace_na(shared, 0),
    AF_only = AF - shared,
    AD_only = AD - shared,
    union = AF + AD - shared,
    jaccard = shared / union
  )

# Average across strains for compact main plot
overlap_protein <- overlap_full %>%
  group_by(protein) %>%
  summarise(
    AF_only = mean(AF_only),
    Shared = mean(shared),
    AD_only = mean(AD_only),
    mean_jaccard = mean(jaccard),
    .groups = "drop"
  )

overlap_long <- overlap_protein %>%
  select(protein, `AD only` = AD_only, Shared, `AF only` = AF_only) %>%
  pivot_longer(
    cols = c("AD only", "Shared", "AF only"),
    names_to = "category",
    values_to = "n"
  ) %>%
  mutate(
    category = factor(category, levels = c("AD only", "Shared", "AF only"))
  )

p1a <- ggplot(overlap_long, aes(x = protein, y = n, fill = category)) +
  geom_col(width = 0.72, color = "black", linewidth = 0.1) +
  scale_fill_manual(values = set_cols) +
  labs(
    x = NULL,
    y = "Mean no. of ligands",
    title = "Top-100 ligand overlap"
  ) +
  theme_nature_small(base_size = 10) +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1),
    legend.position = "top"
  )
print(p1a)

p1b <- ggplot(overlap_full, aes(x = protein, y = jaccard)) +
  geom_boxplot(width = 0.4, outlier.shape = NA, linewidth = 0.3, fill = "grey90") +
  geom_point(
    aes(color = strain),
    position = position_jitter(width = 0.12, height = 0),
    size = 1.4,
    alpha = 0.9
  ) +
  labs(
    x = NULL,
    y = "Jaccard overlap",
    title = "AF–AD ligand-set similarity"
  ) +
  theme_nature_small(base_size = 10) +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1),
    legend.position = "right"
  )
print(p1b)

fig1 <- p1a + p1b + plot_layout(widths = c(1.3, 1))

ggsave(
  file.path(outdir, "Fig1_ligand_overlap_AF_AD.pdf"),
  fig1,
  width = 8,
  height = 4.0,
  units = "in"
)

#####----- Figure 2. AF and AD interaction-type profiles for all top-100 ligands -----#####
# This is your back-to-back barplot idea.
# makes one small plot per protein
plot_interaction_back_to_back <- function(protein_id,
                                          strain_filter = NULL,
                                          shared_only = FALSE,
                                          title_prefix = "All top-100 ligands") {
  
  df <- counts_df %>%
    filter(protein == protein_id)
  
  if (!is.null(strain_filter)) {
    df <- df %>% filter(strain == strain_filter)
  }
  
  if (shared_only) {
    shared_keys <- complex_df %>%
      filter(status == "success") %>%
      distinct(method, strain, protein, EBC_ID) %>%
      group_by(strain, protein, EBC_ID) %>%
      summarise(n_methods = n_distinct(method), .groups = "drop") %>%
      filter(n_methods == 2) %>%
      select(strain, protein, EBC_ID)
    
    df <- df %>%
      semi_join(shared_keys, by = c("strain", "protein", "EBC_ID"))
  }
  
  plot_df <- df %>%
    group_by(method, interaction_type) %>%
    summarise(
      mean_count = mean(count, na.rm = TRUE),
      total_count = sum(count, na.rm = TRUE),
      n_complexes = n(),
      .groups = "drop"
    ) %>%
    mutate(
      signed_mean = if_else(method == "AD", -mean_count, mean_count),
      interaction_type = factor(interaction_type, levels = rev(interaction_levels))
    )
  
  max_x <- max(abs(plot_df$signed_mean), na.rm = TRUE)
  
  ggplot(plot_df, aes(x = signed_mean, y = interaction_type, fill = method)) +
    geom_col(width = 0.68, color = "black", linewidth = 0.12) +
    geom_vline(xintercept = 0, linewidth = 0.35) +
    scale_fill_manual(values = method_cols) +
    scale_x_continuous(
      limits = c(-max_x * 1.15, max_x * 1.15),
      labels = function(x) abs(x)
    ) +
    scale_y_discrete(labels = interaction_labels) +
    labs(
      x = "Mean interactions per ligand",
      y = NULL,
      title = paste0(title_prefix, ": ", protein_id)
    ) +
    theme_nature_small(base_size = 9) +
    theme(
      legend.position = "top",
      plot.title = element_text(size = 9, face = "bold")
    )
}

# Example: make OPG174 plot
p2_opg174 <- plot_interaction_back_to_back("OPG174")
print(p2_opg174)
ggsave(
  file.path(outdir, "Fig2_back_to_back_all_ligands_OPG174.pdf"),
  p2_opg174,
  width = 3.5,
  height = 2.7,
  units = "in"
)

# Generate one PDF per protein
for (p in protein_levels) {
  p_plot <- plot_interaction_back_to_back(p)
  ggsave(
    file.path(outdir, paste0("Fig2_back_to_back_all_ligands_", p, ".pdf")),
    p_plot,
    width = 3.5,
    height = 2.7,
    units = "in"
  )
}

# compact heatmap for Figure 2
fig2_heatmap_df <- counts_df %>%
  group_by(protein, method, interaction_type) %>%
  summarise(mean_count = mean(count, na.rm = TRUE), .groups = "drop") %>%
  pivot_wider(
    names_from = method,
    values_from = mean_count,
    values_fill = 0
  ) %>%
  mutate(
    AF_minus_AD = AF - AD,
    protein = factor(protein, levels = protein_levels),
    interaction_type = factor(interaction_type, levels = rev(interaction_levels))
  )

p2_heatmap <- ggplot(fig2_heatmap_df, aes(x = protein, y = interaction_type, fill = AF_minus_AD)) +
  geom_tile(color = "white", linewidth = 0.25) +
  scale_y_discrete(labels = interaction_labels) +
  scale_fill_gradient2(
    low = method_cols["AD"],
    mid = "white",
    high = method_cols["AF"],
    midpoint = 0,
    name = "AF − AD"
  ) +
  labs(
    x = NULL,
    y = NULL,
    title = "Difference in interaction profiles"
  ) +
  theme_nature_small(base_size = 9) +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1),
    legend.position = "right"
  )
p2_heatmap
ggsave(
  file.path(outdir, "Fig2_heatmap_AF_minus_AD_all_ligands.pdf"),
  p2_heatmap,
  width = 4.2,
  height = 2.7,
  units = "in"
)

#####----- Figure 3. Shared ligands only: AF and AD still differ -----#####
# This is critical because it controls for ligand identity.
# Generate one shared-ligand back-to-back plot per protein
for (p in protein_levels) {
  p_plot <- plot_interaction_back_to_back(
    protein_id = p,
    shared_only = TRUE,
    title_prefix = "Shared ligands only"
  )
  
  ggsave(
    file.path(outdir, paste0("Fig3_back_to_back_shared_ligands_", p, ".pdf")),
    p_plot,
    width = 3.5,
    height = 2.7,
    units = "in"
  )
}

# A paired ligand-level scatterplot is also useful:
shared_keys <- complex_df %>%
  filter(status == "success") %>%
  distinct(method, strain, protein, EBC_ID) %>%
  group_by(strain, protein, EBC_ID) %>%
  summarise(n_methods = n_distinct(method), .groups = "drop") %>%
  filter(n_methods == 2) %>%
  select(strain, protein, EBC_ID)

shared_total <- complex_df %>%
  semi_join(shared_keys, by = c("strain", "protein", "EBC_ID")) %>%
  select(method, strain, protein, EBC_ID, total_interactions) %>%
  group_by(method, strain, protein, EBC_ID) %>%
  summarise(total_interactions = sum(total_interactions, na.rm = TRUE), .groups = "drop") %>%
  pivot_wider(
    names_from = method,
    values_from = total_interactions,
    values_fill = 0
  ) %>%
  mutate(
    protein = factor(protein, levels = protein_levels)
  )

p3_scatter <- ggplot(shared_total, aes(x = AD, y = AF)) +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", linewidth = 0.35, color = "grey40") +
  geom_point(size = 1.1, alpha = 0.65, color = "black") +
  facet_wrap(~ protein, ncol = 4, scales = "free") +
  labs(
    x = "AD total interactions",
    y = "AF total interactions",
    title = "Shared ligands: total interaction counts"
  ) +
  theme_nature_small(base_size = 9) +
  theme(
    axis.text.x = element_text(angle = 90)
  )

ggsave(
  file.path(outdir, "Fig3_shared_ligands_total_interaction_scatter.pdf"),
  p3_scatter,
  width = 8.5,
  height = 5,
  units = "in"
)

#####----- Figure 4. Interaction fingerprint and residue-contact similarity -----#####
# This tests whether the same ligand has similar or different binding fingerprints between AF and AD.
# 4A. Interaction-type fingerprint similarity
calc_cosine <- function(a, b) {
  a <- as.numeric(a)
  b <- as.numeric(b)
  denom <- sqrt(sum(a^2)) * sqrt(sum(b^2))
  if (denom == 0) return(NA_real_)
  sum(a * b) / denom
}

calc_bray_curtis <- function(a, b) {
  a <- as.numeric(a)
  b <- as.numeric(b)
  denom <- sum(a + b)
  if (denom == 0) return(NA_real_)
  sum(abs(a - b)) / denom
}

fp_df <- counts_df %>%
  semi_join(shared_keys, by = c("strain", "protein", "EBC_ID")) %>%
  group_by(method, strain, protein, EBC_ID, interaction_type) %>%
  summarise(count = sum(count, na.rm = TRUE), .groups = "drop") %>%
  complete(
    method,
    strain,
    protein,
    EBC_ID,
    interaction_type = factor(interaction_levels, levels = interaction_levels),
    fill = list(count = 0)
  ) %>%
  unite("method_interaction", method, interaction_type, remove = FALSE) %>%
  select(strain, protein, EBC_ID, method_interaction, count) %>%
  pivot_wider(
    names_from = method_interaction,
    values_from = count,
    values_fill = 0
  )

# Add missing columns if any interaction type is absent
for (itype in interaction_levels) {
  for (m in c("AD", "AF")) {
    col <- paste(m, itype, sep = "_")
    if (!col %in% colnames(fp_df)) {
      fp_df[[col]] <- 0
    }
  }
}

ad_cols <- paste("AD", interaction_levels, sep = "_")
af_cols <- paste("AF", interaction_levels, sep = "_")

fp_sim <- fp_df %>%
  rowwise() %>%
  mutate(
    fingerprint_cosine = calc_cosine(c_across(all_of(ad_cols)), c_across(all_of(af_cols))),
    fingerprint_bray_curtis = calc_bray_curtis(c_across(all_of(ad_cols)), c_across(all_of(af_cols)))
  ) %>%
  ungroup() %>%
  mutate(
    protein = factor(protein, levels = protein_levels)
  )

p4a <- ggplot(fp_sim, aes(x = protein, y = fingerprint_cosine)) +
  geom_boxplot(width = 0.4, outlier.shape = NA, linewidth = 0.3, fill = "grey90") +
  geom_point(
    aes(color = strain),
    position = position_jitter(width = 0.1, height = 0),
    size = 1.0,
    alpha = 0.7
  ) +
  labs(
    x = NULL,
    y = "AF–AD cosine similarity",
    title = "Interaction-type fingerprint similarity"
  ) +
  theme_nature_small(base_size = 9) +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1),
    legend.position = "right"
  )
print(p4a)
ggsave(
  file.path(outdir, "Fig4A_fingerprint_cosine_similarity.pdf"),
  p4a,
  width = 5,
  height = 3,
  units = "in"
)
 
# 4B. Residue-contact rewiring
# This asks: does the same ligand contact the same residues in AF and AD?
calc_jaccard <- function(x, y) {
  x <- unique(na.omit(x))
  y <- unique(na.omit(y))
  x <- x[x != ""]
  y <- y[y != ""]
  
  u <- union(x, y)
  if (length(u) == 0) return(NA_real_)
  
  length(intersect(x, y)) / length(u)
}

res_sets <- inter_df %>%
  semi_join(shared_keys, by = c("strain", "protein", "EBC_ID")) %>%
  filter(!is.na(protein_residue), protein_residue != "") %>%
  mutate(
    residue_contact = protein_residue,
    residue_interaction_contact = paste(protein_residue, interaction_type, sep = "|")
  ) %>%
  group_by(method, strain, protein, EBC_ID) %>%
  summarise(
    residue_set = list(unique(residue_contact)),
    residue_interaction_set = list(unique(residue_interaction_contact)),
    .groups = "drop"
  ) %>%
  pivot_wider(
    names_from = method,
    values_from = c(residue_set, residue_interaction_set)
  )

# Replace missing list columns with empty vectors
empty_list <- list(character(0))

for (col in c(
  "residue_set_AD", "residue_set_AF",
  "residue_interaction_set_AD", "residue_interaction_set_AF"
)) {
  if (!col %in% colnames(res_sets)) {
    res_sets[[col]] <- replicate(nrow(res_sets), character(0), simplify = FALSE)
  }
}

res_sim <- res_sets %>%
  rowwise() %>%
  mutate(
    residue_jaccard = calc_jaccard(residue_set_AD, residue_set_AF),
    residue_interaction_jaccard = calc_jaccard(
      residue_interaction_set_AD,
      residue_interaction_set_AF
    )
  ) %>%
  ungroup() %>%
  mutate(
    protein = factor(protein, levels = protein_levels)
  )

p4b <- ggplot(res_sim, aes(x = protein, y = residue_interaction_jaccard)) +
  geom_boxplot(width = 0.4, outlier.shape = NA, linewidth = 0.3, fill = "grey90") +
  geom_point(
    aes(color = strain),
    position = position_jitter(width = 0.1, height = 0),
    size = 1.0,
    alpha = 0.7
  ) +
  labs(
    x = NULL,
    y = "Residue + interaction Jaccard",
    title = "Residue-level binding rewiring"
  ) +
  theme_nature_small(base_size = 9) +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1),
    legend.position = "right"
  )
print(p4b)
ggsave(
  file.path(outdir, "Fig4B_residue_interaction_jaccard.pdf"),
  p4b,
  width = 5,
  height = 3,
  units = "in"
)

# 4C. Combine Figure 4A and 4B
fig4 <- p4a + p4b + plot_layout(widths = c(1, 1))

ggsave(
  file.path(outdir, "Fig4_fingerprint_and_residue_rewiring.pdf"),
  fig4,
  width = 8,
  height = 3,
  units = "in"
)

